### ISSUE TITLE
Jenkins LTS offers upgrade to Weekly as of Jenkins 2.479.2

### ISSUE THREAD

**Issue by szjozsef** [jenkins-infra/jenkins-infra#3755] opened 2024-11-28 08:58 UTC
### Reproduction steps

After upgrading to LTS 2.479.2 Jenkins begin to offer to update to the Weekly release: 2.487

### Expected Results

Jenkins should offer to upgrade just to the LTS releases

### Actual Results

Jenkins offer to upgrade to the Weekly release: 2.487

### Anything else?

Also the Alert appears that there is a new Jenkins Release available

**Comment by timja** [comment] 2024-11-28 09:00
Duplicate of https://github.com/jenkins-infra/helpdesk/issues/4427

**Closed as not planned by timja** 2024-11-28 09:00 UTC
Labels: bug
